TWITTER_CONSUMER_KEY = 'PUT HERE YOUR CONSUMER KEY'
TWITTER_CONSUMER_SECRET = 'PUT HERE YOUR CONSUMER SECRET'
TWITTER_ACCESS_TOKEN = 'PUT HERE YOUR ACCESS TOKEN'
TWITTER_ACCESS_TOKEN_SECRET = 'PUT HERE YOUR ACCESS TOKEN SECRET'
