# Generated by Django 3.2.7 on 2021-10-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64)),
                ('BirthDate', models.DateTimeField()),
                ('Sex', models.CharField(max_length=1)),
            ],
        ),
    ]
